# Generated by Django 3.0.3 on 2020-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10, null=True)),
                ('price_sale', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
